### PR TITLE
Organize tests into classes

### LINKED ISSUE #213: Fix and reintegrate commented out tests

### PR DESCRIPTION
**Pull request by mttwc**
Refactor tests to minimize use of globals by using classes. They should also look much neater because of clearer formatting.

Also Fixes #213

### CODE REVIEW

**Comment by mttwc** [comment]
@larsendaniel feel free to chip in your 2c!

**Comment by mttwc** [comment]
After lots of investigating with browserify caching, it's actually creating more overhead with all the files being written, I will remove those changes.

**Comment by larsendaniel** [comment]
Yup, this looks right to me.  👍

**Comment by larsendaniel** [comment]
Hmmm, actually I noticed that we still need the following blocks that I had to put in.  `protected afterEach() {
        Settings.setSettingsJsonForTesting(undefined);
    }`

So the tests can still potentially affect each other.  But this is still a good fix.  :shipit:

**Comment by mttwc** [comment]
Yep, that's because we use static state in a lot of places, which is a little unfortunate. I can perhaps move some of this into the base abstract class so we don't have to remember to do it.

**Review by leakymemory — APPROVED** [review]

**Pull request merged**
